# config/train_rl.yaml 
defaults:
  - vehicle: default
  - envs: default 
  - planner: pure_pursuit
  - reward: ???
  - agent: sac
  - buffer: off_policy

num_episodes: 1000
num_steps: 10000
batch_size: 256

eval_interval: 50
eval_episodes: 1

scan_n: 2
dowansample_beam: 60
steer_range: 0.4
speed_range: ${envs.map.speed}

render: false
render_mode: human ## human or human_fast

log_dir: ./logs/train_rl/
ckpt_dir: ./ckpts/${now:%H-%M-%S}

hydra:
  run:
    dir: ./outputs/train_rl/${now:%Y-%m-%d}/${now:%H-%M-%S}